/* Day One MVP™ — interior service-page extension content.
   Adds two sections to every service: "How DOM approaches it" (approach)
   and "Who it's for" (whoFor). Merged onto window.BUILD.services by build.js.
   Loaded after build-data.js + build-data-2.js. Voice: calm, capable, founder-led. */
/* Category-hub content (Part 1 of the research-led expansion) — merged onto
   window.BUILD.categories by build.js. One research stat max per hub. */
window.BUILD_CAT_EXT = {
  "start-the-company": {
    heroQuestion:"What does the idea need to become a real company?",
    explanation:"A company begins before the website, logo, or application. It begins with a real customer, a meaningful problem, a clear offer, a responsible price, and a reason for people to believe the company should exist. We help turn an unfinished idea into a structured business people can understand, trust, buy from, support, or invest in.",
    research:{ title:"Small does not mean insignificant.", body:"Small businesses employ nearly half of America's private-sector workforce. Building stronger small companies is economic development — not merely website design." },
    problems:["I have several ideas and don't know which one to build.","I can't explain the business clearly.","I don't know who the customer is.","I don't know what to charge.","I have a name but no real offer.","I need something to show a partner or investor.","I started building before designing the business."],
    jackQuestion:"If someone gave you sixty seconds, could you explain who this is for, what it changes, and why it should exist?",
    ctaLabel:"Design My Company" },
  "build-the-product": {
    heroQuestion:"What is the smallest working product that can prove the idea?",
    explanation:"A product is not every feature the founder can imagine. It is the smallest responsible experience capable of helping the intended user, demonstrating the concept, and generating useful evidence about what should happen next. We build products around the main user journey — not around feature volume.",
    note:{ title:"Not every idea needs an app.", body:"The right first product may be a focused landing page, a working prototype, a booking system, a customer portal, a private internal tool, an automated intake process, a complete MVP — or no software yet." },
    problems:["I need somebody to build my app.","I have sketches but no functioning product.","My website explains the business but doesn't perform useful actions.","My customers need accounts, bookings, payments, updates, or dashboards.","My team is managing everything manually.","I need a prototype for a meeting.","I need a working version people can test."],
    jackQuestion:"What is the one action your user must be able to complete for this product to matter?",
    ctaLabel:"Find My First Product" },
  "install-the-systems": {
    heroQuestion:"What keeps the business running after the customer says yes?",
    explanation:"Many businesses don't suffer from a lack of ideas. They suffer from disconnected tools, missed messages, unclear responsibilities, repeated manual work, lost customer information, inconsistent follow-up, and systems that depend on one exhausted person remembering everything. We help connect the work into a visible, teachable operating system.",
    research:{ title:"Technology advantage shouldn't belong only to larger companies.", body:"Larger organizations currently adopt AI at higher rates than the broader business population. AIBridge™ exists to help smaller organizations gain practical access without adopting tools they don't understand." },
    problems:["Missed calls and inquiries.","Leads receiving no follow-up.","Customer information stored in several places.","Staff repeating the same work.","No clear onboarding.","No usable reporting.","Nobody knows the current status.","Important information lives only in one person's head.","AI tools used without rules or training."],
    principle:"Automate the repetition. Preserve human judgment.",
    jackQuestion:"What does your company repeat every day that should already be organized?",
    ctaLabel:"Map My Systems" },
  "grow-the-business": {
    heroQuestion:"What turns attention into a customer?",
    explanation:"Marketing creates awareness. Sales creates decisions. Follow-up protects opportunities. Customer experience creates retention. We connect those pieces so growth doesn't depend on random posting, one advertisement, or remembering to call someone back.",
    principle:"Attention → Understanding → Trust → Action → Follow-Up → Experience → Retention → Referral",
    problems:["The business gets attention but few inquiries.","Leads arrive but aren't followed up.","The offer is difficult to understand.","The website attracts the wrong people.","The founder relies entirely on referrals.","The business can't track where customers came from.","Customers purchase once and disappear.","There's no review or referral system."],
    jackQuestion:"If ten qualified people arrived today, what system would turn them into customers?",
    ctaLabel:"Find the Growth Gap" },
  "train-the-people": {
    heroQuestion:"Can the people using the system actually operate it?",
    explanation:"A strong system can still fail when nobody understands it. Training shouldn't be an afterthought, a forgotten PDF, or a one-hour demo delivered on launch day. We can build training into the product, the workflow, the company, and the employee experience.",
    principle:"Explain → Demonstrate → Practice → Review → Apply → Reinforce",
    problems:["Employees are given tools without instruction.","Sales reps use inconsistent language.","New hires learn by guessing.","The founder is the only person who knows the process.","AI is introduced without standards.","Training materials become outdated.","Employees watch videos but never practice.","No one can confirm whether learning transferred into performance."],
    jackQuestion:"Could a new person learn this correctly without standing beside you for three months?",
    ctaLabel:"Build My Training System" },
  "produce-the-media": {
    heroQuestion:"How will people see, hear, and understand the value?",
    explanation:"A strong company can stay invisible when its value is hard to explain. Media gives the company a voice, a face, a demonstration, a teaching tool, and a body of proof. We help create media connected to a business purpose — not content produced only to fill a calendar.",
    problems:["The company is difficult to explain.","The founder is invisible.","Products are shown but never demonstrated.","Long-form content is never repurposed.","Training exists only as spoken instruction.","The business posts often but creates no action.","Audio and video feel disconnected from the sales process.","Valuable conversations disappear after they happen."],
    jackQuestion:"What would someone need to see or hear before they trusted what you do?",
    ctaLabel:"Plan My Media System" }
};

window.BUILD_EXT = {

  /* ===== WORLD 1 — START THE COMPANY ===== */
  "idea-discovery": { approach:"We pull the idea apart with you, separate the three ideas hiding inside it, and pressure-test which one is worth building first — before a dollar goes into code.", whoFor:"Founders sitting on a big idea they can't quite say in one sentence yet, and anyone tempted to build before they've decided which version to build." },
  "customer-definition": { approach:"We work backward from the person in real pain — patterns, plain questions, the words they already use — until the customer is specific enough to design for.", whoFor:"Founders marketing to 'everyone,' and teams whose message feels vague because the audience was never actually named." },
  "positioning": { approach:"We name the real alternatives, find the one place you clearly win, and write it as a sentence the whole company can repeat.", whoFor:"Businesses getting pushed into competing on price, and founders whose offer currently sounds like everyone else's." },
  "offer-design": { approach:"We shape the promise, scope, and terms until a stranger understands it in one read — then strip out everything that creates hesitation.", whoFor:"Founders with real capability but a fuzzy offer, and anyone whose 'custom, hourly' pitch keeps stalling." },
  "pricing": { approach:"We price off the customer's outcome, not your costs — building the number, the tiers, and the value story that makes it believable.", whoFor:"Founders guessing at price, undercharging out of fear, or watching 'starting at' quotes balloon and erode trust." },
  "revenue-model": { approach:"We map how money should come in and repeat — what's one-time, recurring, or expandable — so good months turn into a stable machine.", whoFor:"Service businesses starting from zero every month, and founders who want predictable revenue instead of one-off spikes." },
  "naming": { approach:"We generate directions, check domains and handles in the same pass, and shortlist names you can say at a noisy event and still be found later.", whoFor:"New companies and products, and founders attached to a clever name they haven't checked the availability of." },
  "brand-architecture": { approach:"We map how the company, products, and sub-brands relate, and set simple rules for where the next offer lives — before clutter sets in.", whoFor:"Founders adding offers fast, and businesses where every new product keeps spawning a new brand nobody can navigate." },
  "company-structure": { approach:"We define roles, decisions, and money flow in the simplest frame that works — even if it's one person wearing clearly labeled hats today.", whoFor:"Solo founders and small teams where everything depends on one person's memory, and anyone whose growth keeps breaking the founder." },
  "launch-planning": { approach:"We plan the first audience, the message, and the first weeks as a controlled rollout — not a single silent 'we're live.'", whoFor:"Founders about to launch something nobody knows about yet, and teams who built quietly and now need a real entrance." },
  "investor-partner-materials": { approach:"We turn the company into a one-read story — problem, model, ask — clear and honest enough to survive scrutiny.", whoFor:"Founders raising money or seeking partners, and anyone whose deck is a 40-slide maze that loses people before the conversation starts." },

  /* ===== WORLD 2 — BUILD THE PRODUCT ===== */
  "websites": { approach:"We design around the one action that matters, then build it fast, clear, and backed with proof — looks serve the goal, not the other way around.", whoFor:"Businesses whose first impression happens online, and anyone whose current site looks fine but doesn't turn visitors into inquiries." },
  "web-applications": { approach:"We nail the single core action first, then build the accounts and flows around it — proving demand before piling on features.", whoFor:"Founders whose customers need to do something, not just read, and teams outgrowing a brochure site." },
  "mvps": { approach:"We define the smallest version that still works and feels real, ship it to actual users, and turn what we learn into the next build.", whoFor:"Founders about to bet everything on a big guess, and anyone who needs real proof before scaling." },
  "customer-portals": { approach:"We find the handful of things customers keep asking for, put them behind a secure login, and deliberately leave the rest out.", whoFor:"Service businesses drowning in status emails, and founders whose clients would happily self-serve if given the door." },
  "staff-portals": { approach:"We fix the workflow first, then give the team one place to run the daily work — roles, records, and tasks, not a prettier spreadsheet.", whoFor:"Owners whose team texts them all day, and businesses running on scattered tools and tribal knowledge." },
  "dashboards": { approach:"We pick the few numbers that actually drive action and put them on one live screen — no vanity metrics.", whoFor:"Owners steering by gut, and founders who can't answer 'how's the business doing?' without digging." },
  "booking-systems": { approach:"We make the booking link the obvious next step and wire in reminders and calendar sync to kill no-shows and phone tag.", whoFor:"Appointment-based businesses losing time to scheduling back-and-forth, and anyone bleeding bookings to slow replies." },
  "quote-systems": { approach:"We build a guided estimate flow with consistent pricing logic so a real number reaches the customer in minutes, not days.", whoFor:"Service businesses where quoting is the bottleneck, and founders losing deals to whoever answered first." },
  "marketplaces": { approach:"We figure out which side is harder, win that one first, and build the listings, matching, and trust the model needs to not launch empty.", whoFor:"Founders connecting two groups — buyers and sellers, clients and providers — who have to solve both sides at once." },
  "membership-platforms": { approach:"We build the access, billing, and gated value, and design a real reason to stay — not just a reason to sign up once.", whoFor:"Experts and creators with ongoing value to offer, and founders who want recurring revenue instead of one-time sales." },
  "internal-tools": { approach:"We target the one manual task eating your day and build the small purpose-fit tool that erases it — instead of five subscriptions.", whoFor:"Teams bending generic software to fit, and owners doing the same manual busywork every single day." },
  "specialized-digital-products": { approach:"We build for the niche need head-on — the thing off-the-shelf tools never quite fit — and turn it into a hard-to-copy edge.", whoFor:"Industries still running on paper or spreadsheets, and founders whose advantage is a need nobody else serves." },

  /* ===== WORLD 3 — INSTALL THE SYSTEMS ===== */
  "ai-assistants": { approach:"We train an assistant on your real answers and tone, let it handle the repetitive 80%, and keep a human in the loop where it counts.", whoFor:"Teams answering the same questions over and over, and businesses fielding after-hours requests staff shouldn't have to." },
  "crm-systems": { approach:"We give every lead and conversation one home, set the pipeline stages, and wire the follow-up reminders so nothing slips.", whoFor:"Businesses tracking leads across a notebook, an inbox, and a phone, and anyone losing deals because no one followed up." },
  "automation": { approach:"We map the repetitive steps, fix the process first, then let triggers handle the robot work — with review where it matters.", whoFor:"Owners doing the same manual sends and updates daily, and teams whose busywork breaks the moment volume rises." },
  "lead-routing": { approach:"We set rules that send each new lead to the right owner instantly, so speed-to-lead becomes your advantage, not your leak.", whoFor:"Teams juggling multiple offers or reps, and businesses where leads sit in an inbox nobody watches." },
  "email-sms-workflows": { approach:"We build triggered sequences — welcomes, reminders, follow-ups — that send the right message at the right moment, helpful not spammy.", whoFor:"Businesses hoping customers come back on their own, and founders who never built the follow-up where sales actually close." },
  "onboarding": { approach:"We design a guided first experience that gets new customers to their first win fast — cutting refunds, churn, and confusion.", whoFor:"Founders losing people right after the sale, and teams whose new customers don't know what to do next." },
  "reporting": { approach:"We turn raw activity into a clear, regular answer to 'what's working and what's next' — in plain language, tied to a decision.", whoFor:"Owners steering by vibes, and founders who keep making the same decision blind." },
  "knowledge-systems": { approach:"We document how the business actually works into a searchable base that powers training and AI — so it's not trapped in one head.", whoFor:"Businesses where one person holds all the answers, and teams where every absence becomes a crisis." },
  "staff-workflows": { approach:"We map the repeatable steps and clean handoffs, then train the team to run them like operators — so the system works without depending on heroics, tribal knowledge, or you.", whoFor:"Teams where things fall through the cracks between people, and owners who want staff (and sales agents) who can operate the system, not just follow it." },
  "customer-communication": { approach:"We set up the right updates on the right channels at the right moments, so silence never reads as neglect.", whoFor:"Businesses going quiet between sale and delivery, and teams fielding constant 'any update?' calls." },
  "internal-operations": { approach:"We connect the workflows, tools, and data so the business runs as a machine instead of on the owner's back.", whoFor:"Founders who are personally the glue holding everything together, and businesses where growth keeps making everything harder." },

  /* ===== WORLD 4 — GROW THE BUSINESS ===== */
  "offer-design-atom": { approach:"We sharpen the promise, proof, and risk reversal until the offer is a clear yes — the highest-leverage fix before spending on traffic.", whoFor:"Founders driving traffic to an offer that won't convert, and businesses sitting on capability without a productized path." },
  "sales-systems": { approach:"We turn selling into a repeatable path — qualify, quote, follow-up — so revenue doesn't ride on one closer's gut.", whoFor:"Founders carrying all the sales, and teams treating every deal as a one-off scramble." },
  "marketing-campaigns": { approach:"We aim one coordinated push — message, channels, timing — at a single goal over a set window, so effort compounds.", whoFor:"Businesses posting randomly and calling it marketing, and teams who need a specific outcome, not just activity." },
  "lead-generation": { approach:"We win one channel before chasing the next, build a repeatable source for the right inquiries, and track what actually works.", whoFor:"Founders whose revenue is a roller coaster, and businesses depending on word of mouth alone." },
  "follow-up": { approach:"We build the planned touches after first contact — helpful, not pushy — to recover the deals most businesses let quietly die.", whoFor:"Teams that follow up once and quit, and founders leaving money in messages they never send." },
  "content-strategy": { approach:"We plan useful, on-brand content with a cadence you can keep, compounding into authority and inbound instead of random posting.", whoFor:"Founders posting for the algorithm, and experts who want to be the obvious choice in their market." },
  "local-seo": { approach:"We optimize the profile, reviews, and listings that put you in the local map pack — where the calls actually come from.", whoFor:"Local service businesses invisible on the map, and owners relying on referrals while neighbors are searching right now." },
  "search-readiness": { approach:"We make the site clear, fast, and structured enough that search engines and AI answers can understand and recommend you.", whoFor:"Businesses with beautiful sites that machines can't read, and founders who want to be the answer AI picks." },
  "reputation": { approach:"We build the review systems and trust signals that shape perception before a sales conversation ever starts.", whoFor:"Businesses being compared against competitors, and founders whose proof doesn't yet match the quality of their work." },
  "referral-systems": { approach:"We create the prompts, process, and incentives that turn happy customers and partners into a deliberate, repeatable source of growth.", whoFor:"Businesses hoping people remember to refer them, and founders sitting on goodwill they've never systematized." },
  "conversion-improvement": { approach:"We find the friction — message, flow, proof, forms — slowing decisions, and remove it so more of the same traffic acts.", whoFor:"Businesses with traffic that doesn't convert, and founders guessing at why visitors don't take the next step." },
  "retention": { approach:"We strengthen the experience, communication, and delivery that keep customers paying, returning, and expanding.", whoFor:"Subscription and service businesses losing customers out the back door, and founders over-focused on acquisition alone." },

  /* ===== WORLD 5 — TRAIN THE PEOPLE ===== */
  "ai-foundations": { approach:"We teach practical, responsible AI use built around your real workflows — judgment and application, not hype.", whoFor:"Teams curious but unsure where AI fits, and founders who want real capability, not just buzzwords." },
  "sales-training": { approach:"We train the real conversation — positioning, discovery, objections, follow-up — so the team sells with consistency, not memorized scripts.", whoFor:"Founders who've carried sales alone, and teams whose results swing on who's making the call." },
  "employee-onboarding": { approach:"We design a structured entry — role, systems, expectations — that shortens ramp time and stops depending on ad-hoc explanations.", whoFor:"Growing businesses hiring fast, and owners re-explaining the same basics to every new person." },
  "founder-education": { approach:"We teach founders to think clearly across offer, systems, product, and growth — practical judgment, not generic inspiration.", whoFor:"Founders making decisions across the whole company at once, and operators who want sharper judgment, not a motivational seminar." },
  "operator-training": { approach:"We train your people — sales agents first — to run the machine like operators: the workflows, the offer, the decisions, the reporting, so the work moves without routing back through you.", whoFor:"Teams whose agents stall the moment a conversation goes off-script, and founders ready to turn order-takers into operators who can think and move the work." },
  "workshops": { approach:"We run focused working sessions on one real problem — strategy, offer, systems — to make progress instead of circling it.", whoFor:"Teams stuck on a specific decision, and founders who want the right people in one room making real headway." },
  "internal-academies": { approach:"We design the curriculum, structure, and systems that turn your own methods and standards into repeatable training at scale.", whoFor:"Companies wanting consistent team capability, and founders ready to teach their way of working as a system." },
  "training-videos": { approach:"We produce clear training media for the things you explain more than once — workflows, tools, expectations people can revisit.", whoFor:"Businesses repeating the same explanations, and teams onboarding or rolling out change at scale." },
  "learning-portals": { approach:"We build the digital home where teams, clients, or communities access lessons, progress, and materials in one structured place.", whoFor:"Organizations delivering ongoing training, and founders who want education that's easy to manage, track, and expand." },
  "role-play-systems": { approach:"We build practice environments where people rehearse high-stakes conversations before the real moment — active and measurable, not passive.", whoFor:"Sales, service, and management teams whose performance depends on communication under pressure." },
  "custom-company-programs": { approach:"We build training around your specific model, maturity, and goals — combining content, systems, and delivery when standard training won't fit.", whoFor:"Companies whose needs are too specific for off-the-shelf training, and founders who want something built around their own people." },

  /* ===== WORLD 6 — PRODUCE THE MEDIA ===== */
  "audio": { approach:"We create clear, intentional audio that fits the use — education, story, promotion — so sound carries the message where text can't.", whoFor:"Brands and founders whose message lands better heard than read, and teams needing consistent, quality audio assets." },
  "video": { approach:"We build video around the job it must do — explain, demonstrate, persuade — so it moves people, not just fills a feed.", whoFor:"Businesses with something to show, and founders who want presence and clarity in a faster, more human format." },
  "podcasts": { approach:"We shape the format, workflow, and publishing system so the show becomes a repeatable asset, not a side experiment.", whoFor:"Founders building voice and audience, and brands who want a long-form channel for perspective and relationships." },
  "product-demonstrations": { approach:"We show the core value and key flow clearly — enough to make the decision feel easy and safe, without drowning viewers in detail.", whoFor:"Software, platforms, and complex offers where seeing it work closes the gap words can't." },
  "founder-content": { approach:"We turn your ideas, lessons, and expertise into structured content that builds authority without sounding manufactured.", whoFor:"Founders who want a clear public voice, and businesses where the leader's credibility drives sales, hiring, and partnerships." },
  "social-clips": { approach:"We cut larger ideas into fast, reusable clips built for attention and distribution — without a separate content engine per platform.", whoFor:"Founders and brands sitting on long-form material, and teams who want reach without doubling the workload." },
  "training-media": { approach:"We produce media built for internal education — onboarding, process, capability — so important knowledge is easy to deliver and retain.", whoFor:"Growing teams that need to teach at scale, and businesses where performance depends on consistent instruction." },
  "commercial-content": { approach:"We create media built to support a sale, launch, or campaign — clear messaging that moves the audience toward a defined action.", whoFor:"Businesses running ads, launches, or direct-response, and founders who need content that sells, not just looks good." },
  "campaign-media": { approach:"We produce the visual and narrative assets a growth push needs across channels — coordinated to one objective, not scattered.", whoFor:"Teams launching a campaign or offer, and businesses who want a deliberate push instead of disconnected materials." },
  "sound-design": { approach:"We craft the sonic layer — pacing, tone, emphasis — that makes media feel polished and immersive, even when viewers can't name why.", whoFor:"Brands and creators producing video and experiences who want the felt difference of professional sound." },
  "voiceover": { approach:"We produce voiceover that guides without overperforming — carrying tone and helping the audience follow what matters most.", whoFor:"Training, product, and promotional media where hearing the message improves understanding." },
  "content-repurposing": { approach:"We turn long-form assets into smaller reusable formats across channels — extending the life of strong ideas instead of wasting them.", whoFor:"Businesses producing ongoing content, and founders sitting on source material they've only used once." },
  "publishing-systems": { approach:"We design the workflow behind planning, producing, approving, and releasing media so output stays consistent without constant chaos.", whoFor:"Teams producing ongoing content, and businesses whose media effort burns out before it scales." },
  "skits": { approach:"We write the scene around one clear point, cast and direct it so it lands, and cut it for each platform — entertaining, but always aimed at the offer.", whoFor:"Brands and founders who want attention that's actually watched and shared, and businesses whose message is more memorable acted out than explained." },
  "jingles": { approach:"We write and produce a short, original hook — a few seconds of music built around your brand's feel — and deliver it sized for ads, video, and the phone.", whoFor:"Local businesses and brands who want to be instantly recognizable, and founders who want a sound people remember long after the ad ends." },

  /* added building blocks */
  "market-research": { approach:"We test the idea against real demand — searches, competitors, and honest customer conversations — and give you a clear go, wait, or pivot.", whoFor:"Founders about to invest in an unproven idea, and anyone who's only heard 'great idea' from people who'll never buy." },
  "integrations": { approach:"We map where your tools should hand off to each other and wire the connections so data moves on its own, with checks where it matters.", whoFor:"Businesses re-typing the same data across apps, and teams whose tools each hold a different version of the truth." },
  "certification": { approach:"We build the checks and sign-offs that prove learning turned into performance — so you know who's ready, and who needs another round.", whoFor:"Teams who train but can't confirm it worked, and owners who need consistent quality before people go live." },
  "photography": { approach:"We plan and capture the images your business actually needs — credible, on-brand, and ready to reuse across site, media, and sales.", whoFor:"Businesses leaning on stock or phone photos, and founders whose real quality isn't coming through online." }
};
