/* Day One MVP™ — Tech Answers glossary (central, extensible data source).
   Add terms here; the board renders + searches them automatically.
   Fields: t=term, c=category, d=plain definition, m=what it means for you,
   ex=plain example, w=where it appears in your build, r=related terms. */
window.GLOSSARY = [
  /* ---- Day One System ---- */
  { t: "Day One MVP™", c: "Day One System", d: "The company that turns an idea, business problem, or unfinished concept into a structured company, working product, system, campaign, or launchable first version.", m: "You don't need every answer. You begin with the idea or the problem.", r: ["The G Code™", "MVP"] },
  { t: "The G Code™", c: "Day One System", d: "The documentary and educational platform showing the real process behind building companies, products, systems, and opportunities.", m: "You can see how Jack thinks, teaches, and directs a build before you ever hire the company.", r: ["Day One MVP™"] },
  { t: "AIBridge™", c: "Day One System", d: "The technology, AI, automation, education, and systems layer behind Day One MVP™.", m: "It connects the human problem to practical technology without shutting you out of the process.", r: ["AI Audit", "AI Agent"] },
  { t: "Atom™", c: "Day One System", d: "The sales and market engine used to understand the customer, shape the offer, sharpen the message, answer objections, and turn attention into customers.", ex: "Atom™ helps determine what the business should sell, who should buy it, and why they should care.", r: ["Offer", "Funnel"] },
  { t: "Boris™", c: "Day One System", d: "The monetization and commercial engine used to develop pricing, packages, recurring revenue, margins, and realistic business models.", ex: "Boris™ makes sure a good idea can also function as a real business.", r: ["Business Model", "Recurring Revenue"] },
  { t: "Fenrir™", c: "Day One System", d: "The observation and clarity stage. It examines the idea, people, market, problem, behavior, and risks before a solution is chosen.", ex: "Before building a booking app, Fenrir™ asks whether booking is actually the main problem.", r: ["Odin™", "Idea Audit"] },
  { t: "Odin™", c: "Day One System", d: "The research and structural-analysis stage. It organizes the concept into users, pages, functions, data, business model, and launch path.", r: ["Fenrir™", "Gaia™"] },
  { t: "Gaia™", c: "Day One System", d: "The systemization stage. It turns scattered ideas, files, plans, and decisions into an organized operating structure.", r: ["Odin™", "Thor™"] },
  { t: "Thor™", c: "Day One System", d: "The build and implementation stage. It begins after the idea has been observed, researched, organized, priced, and approved.", ex: "Thor™ is when the hammer comes down and the working product gets built.", r: ["Gaia™", "MVP"] },
  { t: "Maestro Method™", c: "Day One System", d: "The creative method used to direct a project as a coordinated composition rather than a collection of disconnected parts — aligning design, story, product, business, and customer experience.", r: ["Brand System"] },
  { t: "Ask Protocol™", c: "Day One System", d: "A process of asking focused questions until the outcome, audience, visual direction, functionality, and business purpose are sufficiently clear.", r: ["Scope"] },
  { t: "Black Vault Protocol™", c: "Day One System", d: "A confidentiality and controlled-access standard for sensitive ideas, company information, systems, credentials, and proprietary projects.", r: ["NDA", "Access Control"] },

  /* ---- Product Development ---- */
  { t: "Idea Audit", c: "Product Development", d: "A structured review of an idea's customer, problem, timing, competition, revenue potential, risks, and build requirements.", w: "Level 1 — Blueprint & Prototype.", r: ["Blueprint", "Proof of Concept"] },
  { t: "Blueprint", c: "Product Development", d: "The organized plan showing what should be built, who it serves, how it functions, and what should happen first.", w: "Level 1 — Blueprint & Prototype.", r: ["Wireframe", "Roadmap"] },
  { t: "Wireframe", c: "Product Development", d: "A simple structural drawing showing where information, buttons, images, forms, and features belong before visual styling is finalized.", r: ["Prototype", "UI"] },
  { t: "Prototype", c: "Product Development", d: "An early visual or interactive model used to demonstrate how a product may look and behave. It may appear functional without containing complete production systems.", r: ["Wireframe", "Working Alpha"] },
  { t: "Proof of Concept", c: "Product Development", d: "A small technical test used to prove that a difficult feature or idea is possible.", r: ["Prototype"] },
  { t: "MVP", c: "Product Development", d: "Minimum viable product. A working first version with the smallest responsible set of features needed to solve the main problem, serve real users, and collect useful feedback.", m: "Every extra feature adds cost, time, and risk — the MVP proves what should happen next.", w: "Level 3 — MVP Launch.", r: ["Working Alpha", "Beta"] },
  { t: "Working Alpha", c: "Product Development", d: "An early functional product built for controlled testing. It works through its main journey but may still need refinement and expansion.", w: "Level 2 — Working Alpha.", r: ["MVP", "Beta"] },
  { t: "Beta", c: "Product Development", d: "A later testing version shared with a broader audience before the final public release.", r: ["Working Alpha", "Production Version"] },
  { t: "Production Version", c: "Product Development", d: "A version prepared for real customers, real operations, monitoring, support, and ongoing improvement.", r: ["Beta", "Deployment"] },
  { t: "Scope", c: "Product Development", d: "The agreed boundary of what will and will not be built during a project.", m: "Clear scope is how you avoid surprise costs.", r: ["Revision", "Roadmap"] },
  { t: "Revision", c: "Product Development", d: "An approved round of changes to work already included in the project scope — different from adding an entirely new feature.", r: ["Scope"] },
  { t: "Roadmap", c: "Product Development", d: "A prioritized plan showing what should be built now, next, and later.", r: ["Blueprint", "Scope"] },
  { t: "User Journey", c: "Product Development", d: "The series of steps a person takes from first discovering the company to completing an important action.", r: ["User Story", "Funnel"] },
  { t: "Acceptance Criteria", c: "Product Development", d: "The conditions that must be true for a feature to be considered complete and working as agreed.", r: ["Scope", "Quality Assurance"] },

  /* ---- Websites and Applications ---- */
  { t: "Website", c: "Websites and Applications", d: "A collection of public pages used mainly to explain, display, educate, market, or convert.", r: ["Web Application", "Landing Page"] },
  { t: "Web Application", c: "Websites and Applications", d: "A browser-based product that lets users complete meaningful tasks, manage information, use accounts, or operate a system.", r: ["Website", "Dashboard"] },
  { t: "Native Mobile Application", c: "Websites and Applications", d: "An application built specifically for a mobile operating system and distributed through an app store.", r: ["Progressive Web App"] },
  { t: "Progressive Web App", c: "Websites and Applications", d: "A web application that can behave more like a mobile app and may be installable from the browser.", r: ["Web Application"] },
  { t: "Landing Page", c: "Websites and Applications", d: "A focused page designed around one audience, offer, campaign, or action.", r: ["Sales Page", "Conversion"] },
  { t: "Sales Page", c: "Websites and Applications", d: "A page that explains the problem, solution, value, proof, price, objections, and purchasing action.", r: ["Landing Page", "Offer"] },
  { t: "Customer Portal", c: "Websites and Applications", d: "A secure area where customers can view information, manage services, upload files, approve work, pay, or communicate.", r: ["Dashboard", "Authentication"] },
  { t: "Dashboard", c: "Websites and Applications", d: "A screen that summarizes important information, performance, tasks, or activity.", r: ["Admin Dashboard"] },
  { t: "Admin Dashboard", c: "Websites and Applications", d: "A protected area where an owner or authorized employee manages users, content, transactions, settings, and reports.", r: ["User Role", "Authorization"] },
  { t: "CMS", c: "Websites and Applications", d: "Content management system. A tool allowing authorized people to update website content without editing code directly.", r: ["Website"] },
  { t: "Ecommerce", c: "Websites and Applications", d: "Technology supporting products, carts, checkout, payments, orders, and customer accounts.", r: ["Marketplace", "Subscription"] },
  { t: "Marketplace", c: "Websites and Applications", d: "A platform connecting multiple buyers and sellers, providers and customers, or other participating groups.", r: ["Platform", "Marketplace Revenue"] },
  { t: "Membership System", c: "Websites and Applications", d: "A digital system providing controlled access based on account, payment, role, or membership status.", r: ["Subscription", "Authorization"] },
  { t: "Platform", c: "Websites and Applications", d: "A larger digital system supporting several user types, services, transactions, tools, or connected experiences.", w: "Level 4 — Platform Launch.", r: ["Marketplace", "Web Application"] },
  { t: "UI", c: "Websites and Applications", d: "User interface — the visible parts of a product: screens, buttons, menus, forms, cards, icons, and controls.", r: ["UX", "Component"] },
  { t: "UX", c: "Websites and Applications", d: "User experience — how understandable, efficient, comfortable, and useful the complete experience feels to the user.", r: ["UI", "Accessibility"] },
  { t: "Responsive Design", c: "Websites and Applications", d: "A design that adjusts properly across phones, tablets, laptops, and desktop screens.", r: ["Mobile-First"] },
  { t: "Mobile-First", c: "Websites and Applications", d: "Designing the phone experience first rather than shrinking a desktop page after it is already complete.", r: ["Responsive Design"] },
  { t: "Accessibility", c: "Websites and Applications", d: "Designing so people with different abilities can understand, navigate, and use a product — including contrast, keyboard access, readable text, alternative text, and labels.", r: ["UX"] },
  { t: "Design System", c: "Websites and Applications", d: "A reusable collection of colors, fonts, spacing rules, buttons, cards, form elements, and interface patterns.", r: ["Component", "Brand System"] },
  { t: "Component", c: "Websites and Applications", d: "A reusable interface element such as a button, navigation bar, card, form, or modal.", r: ["Design System"] },
  { t: "Information Architecture", c: "Websites and Applications", d: "The way pages, sections, content, and navigation are organized so people can find what they need.", r: ["User Journey"] },

  /* ---- AI and Automation ---- */
  { t: "Artificial Intelligence", c: "AI and Automation", d: "Technology capable of performing tasks involving language, pattern recognition, prediction, classification, generation, or decision support.", r: ["Large Language Model", "AI Agent"] },
  { t: "Large Language Model", c: "AI and Automation", d: "An AI model trained to understand and generate language.", r: ["Prompt", "Custom GPT"] },
  { t: "Prompt", c: "AI and Automation", d: "An instruction, question, context package, or set of rules given to an AI system.", r: ["Custom GPT"] },
  { t: "Custom GPT", c: "AI and Automation", d: "A configured AI assistant designed for a particular role, knowledge area, workflow, or audience.", r: ["AI Agent", "Knowledge Base"] },
  { t: "AI Agent", c: "AI and Automation", d: "An AI-enabled system that can follow instructions, use approved tools, retrieve information, and perform defined actions. Agents require boundaries, permissions, testing, and human oversight.", r: ["Human in the Loop", "AI Governance"] },
  { t: "Automation", c: "AI and Automation", d: "A rule-based process that performs repetitive actions when defined conditions are met.", r: ["Workflow", "Webhook"] },
  { t: "Workflow", c: "AI and Automation", d: "An ordered series of actions, decisions, messages, tasks, and handoffs used to complete a process.", r: ["Automation"] },
  { t: "Human in the Loop", c: "AI and Automation", d: "A system in which a human reviews, approves, corrects, or controls important AI-assisted actions.", r: ["AI Governance", "AI Agent"] },
  { t: "Knowledge Base", c: "AI and Automation", d: "An organized collection of approved company information used by employees, customers, or AI systems.", r: ["Retrieval-Augmented Generation"] },
  { t: "Retrieval-Augmented Generation", c: "AI and Automation", d: "A method allowing an AI system to retrieve approved source information before producing an answer.", ex: "The assistant checks the company's trusted information before answering.", r: ["Knowledge Base", "Hallucination"] },
  { t: "Hallucination", c: "AI and Automation", d: "When an AI system generates information that sounds confident but is inaccurate, invented, or unsupported.", r: ["Human in the Loop"] },
  { t: "AI Governance", c: "AI and Automation", d: "The rules controlling how AI is selected, accessed, monitored, reviewed, and used inside an organization.", r: ["AI Audit", "Access Control"] },
  { t: "AI Audit", c: "AI and Automation", d: "A review of workflows, tools, risks, repetitive tasks, staff pain points, and opportunities for responsible AI implementation.", w: "AI Audit™ — $500–$2,500.", r: ["AIBridge™", "AI Bridge Installation™"] },
  { t: "AI Bridge Installation™", c: "AI and Automation", d: "A structured implementation of AI workspaces, assistants, prompts, workflows, automations, training, and documentation.", w: "AI Bridge Installation™ — $2,500–$10,000.", r: ["AI Audit", "Fractional AI Director™"] },
  { t: "Fractional AI Director™", c: "AI and Automation", d: "An ongoing leadership role helping an organization plan, manage, implement, and improve its AI systems without hiring a full-time executive.", w: "Fractional AI Director™ — from $1,500/mo.", r: ["AI Governance"] },

  /* ---- Data and Infrastructure ---- */
  { t: "Domain", c: "Data and Infrastructure", d: "The public website address, such as DayOneMVP.com.", r: ["Hosting", "Deployment"] },
  { t: "Hosting", c: "Data and Infrastructure", d: "The online infrastructure where the website or application runs.", r: ["Cloud", "Deployment"] },
  { t: "Deployment", c: "Data and Infrastructure", d: "The process of publishing a tested build to a live environment.", r: ["Staging Environment", "Production Environment"] },
  { t: "Database", c: "Data and Infrastructure", d: "An organized system for storing and retrieving information such as users, appointments, orders, messages, products, or reports.", r: ["API"] },
  { t: "API", c: "Data and Infrastructure", d: "Application programming interface. A controlled method allowing two systems to exchange information or request actions.", ex: "An API can let a booking platform send an appointment into a calendar.", r: ["Integration", "Webhook"] },
  { t: "Integration", c: "Data and Infrastructure", d: "A connection between separate tools or systems.", r: ["API", "Webhook"] },
  { t: "Webhook", c: "Data and Infrastructure", d: "An automatic message one system sends to another when a specific event occurs.", ex: "A payment webhook can tell the application that an invoice has been paid.", r: ["API"] },
  { t: "Authentication", c: "Data and Infrastructure", d: "The process used to verify who a user is, usually through login credentials, codes, or approved identity providers.", r: ["Authorization", "User Role"] },
  { t: "Authorization", c: "Data and Infrastructure", d: "The rules determining what an authenticated user is allowed to see or do.", r: ["Authentication", "Access Control"] },
  { t: "User Role", c: "Data and Infrastructure", d: "A permission category such as customer, employee, manager, administrator, vendor, or partner.", r: ["Authorization"] },
  { t: "Cloud", c: "Data and Infrastructure", d: "Remote computing infrastructure used to run software, store data, and provide services through the internet.", r: ["Hosting", "Scalability"] },
  { t: "Environment Variable", c: "Data and Infrastructure", d: "A protected configuration value used for items such as service IDs, domains, and secret keys. Secrets must never be placed directly into public source code.", r: ["Version Control"] },
  { t: "Version Control", c: "Data and Infrastructure", d: "A system that records changes to code and lets builders review, restore, and coordinate work.", r: ["GitHub", "Backup"] },
  { t: "GitHub", c: "Data and Infrastructure", d: "A platform commonly used to store, manage, review, and collaborate on code.", r: ["Version Control"] },
  { t: "Backup", c: "Data and Infrastructure", d: "A protected copy of important data or files used to recover from loss, corruption, or failure.", r: ["Database"] },
  { t: "Staging Environment", c: "Data and Infrastructure", d: "A private or controlled version of the product used for testing before changes are published live.", r: ["Production Environment", "Deployment"] },
  { t: "Production Environment", c: "Data and Infrastructure", d: "The live version used by actual customers and operators.", r: ["Staging Environment"] },
  { t: "Uptime", c: "Data and Infrastructure", d: "The percentage of time a system remains available and operational.", r: ["Scalability"] },
  { t: "Scalability", c: "Data and Infrastructure", d: "The ability of a system to handle growth in users, data, transactions, or activity. We explain what type of growth the current architecture is designed to handle — not as an unsupported promise.", r: ["Cloud"] },

  /* ---- Sales and Marketing ---- */
  { t: "Offer", c: "Sales and Marketing", d: "The complete package a customer is asked to purchase — the outcome, price, process, inclusions, and conditions.", r: ["Value Proposition", "Call to Action"] },
  { t: "Value Proposition", c: "Sales and Marketing", d: "The clearest explanation of why a specific customer should choose this solution.", r: ["Offer", "Ideal Customer"] },
  { t: "Ideal Customer", c: "Sales and Marketing", d: "The type of person or organization most likely to need, value, purchase, and succeed with the offer.", r: ["Qualified Lead"] },
  { t: "Call to Action", c: "Sales and Marketing", d: "The next action the visitor is being asked to take — for example Start My MVP, Submit My Idea, or Watch The G Code™.", r: ["Conversion"] },
  { t: "Lead", c: "Sales and Marketing", d: "A person or organization that has shown potential interest.", r: ["Qualified Lead", "Pipeline"] },
  { t: "Qualified Lead", c: "Sales and Marketing", d: "A lead that meets the conditions required to be a realistic customer.", r: ["Lead", "Lead Routing"] },
  { t: "Funnel", c: "Sales and Marketing", d: "The sequence that moves a person from awareness to interest, decision, purchase, onboarding, and retention.", r: ["Conversion", "Nurture Campaign"] },
  { t: "Lead Magnet", c: "Sales and Marketing", d: "A useful resource offered in exchange for contact information.", r: ["Funnel"] },
  { t: "CRM", c: "Sales and Marketing", d: "Customer relationship management system. Organizes leads, customers, conversations, follow-ups, appointments, and sales opportunities.", r: ["Pipeline", "Lead Routing"] },
  { t: "Pipeline", c: "Sales and Marketing", d: "The stages used to track a lead or customer through a process.", r: ["CRM"] },
  { t: "Lead Routing", c: "Sales and Marketing", d: "The rules determining where a new lead goes and who is responsible for responding.", r: ["CRM"] },
  { t: "Nurture Campaign", c: "Sales and Marketing", d: "A planned sequence of useful messages that educates, builds trust, and guides a lead toward the next action.", r: ["Funnel"] },
  { t: "Conversion", c: "Sales and Marketing", d: "A completed action the company wants to measure — submitting an idea, booking a call, joining a waitlist, purchasing, or donating.", r: ["Conversion Rate", "Attribution"] },
  { t: "Conversion Rate", c: "Sales and Marketing", d: "The percentage of visitors or leads who complete the intended action.", r: ["Conversion"] },
  { t: "SEO", c: "Sales and Marketing", d: "Search engine optimization — the structure and content used to help search engines understand and display a website for relevant searches.", r: ["Local SEO", "Organic Marketing"] },
  { t: "Local SEO", c: "Sales and Marketing", d: "Search optimization focused on a specific city, region, or service area.", r: ["Google Business Profile", "SEO"] },
  { t: "Google Business Profile", c: "Sales and Marketing", d: "The business listing used in Google Search and Maps.", r: ["Local SEO"] },
  { t: "Organic Marketing", c: "Sales and Marketing", d: "Audience growth and customer acquisition that does not rely directly on paid advertising.", r: ["Paid Media", "Content Strategy"] },
  { t: "Paid Media", c: "Sales and Marketing", d: "Advertising purchased through platforms such as Google, Meta, LinkedIn, or TikTok. Advertising spend is separate from project fees unless a proposal states otherwise.", r: ["Retargeting", "Pixel"] },
  { t: "Retargeting", c: "Sales and Marketing", d: "Advertising or follow-up directed toward people who previously visited or interacted with the company.", r: ["Pixel", "Paid Media"] },
  { t: "Pixel", c: "Sales and Marketing", d: "A tracking tool used by an advertising platform to measure site actions and support campaign optimization.", r: ["Analytics", "Attribution"] },
  { t: "Analytics", c: "Sales and Marketing", d: "The measurement of visitors, traffic sources, actions, behavior, and performance.", r: ["UTM Parameter", "Attribution"] },
  { t: "UTM Parameter", c: "Sales and Marketing", d: "A small tracking label added to a link to identify where traffic came from.", r: ["Attribution", "Analytics"] },
  { t: "Attribution", c: "Sales and Marketing", d: "Determining which source, campaign, message, or interaction contributed to a conversion.", r: ["Analytics"] },
  { t: "Content Strategy", c: "Sales and Marketing", d: "The plan for what content should be created, who it is for, where it appears, and what business action it should support.", r: ["Founder-Led Marketing"] },
  { t: "Founder-Led Marketing", c: "Sales and Marketing", d: "Marketing in which the founder's real voice, experience, beliefs, process, and accountability become part of how trust is built.", r: ["Social Proof"] },
  { t: "Social Proof", c: "Sales and Marketing", d: "Real evidence that others have used, valued, supported, or benefited from the company. Never fabricated.", r: ["Founder-Led Marketing"] },

  /* ---- Business and Revenue ---- */
  { t: "Business Model", c: "Business and Revenue", d: "The complete structure explaining how the company creates value, delivers it, and earns revenue.", r: ["Revenue Model", "Boris™"] },
  { t: "Revenue Model", c: "Business and Revenue", d: "The specific method used to generate income.", r: ["Subscription", "One-Time Purchase"] },
  { t: "One-Time Purchase", c: "Business and Revenue", d: "A single payment for a defined product or engagement.", r: ["Subscription"] },
  { t: "Subscription", c: "Business and Revenue", d: "A recurring payment for continued access to a product or service.", r: ["Retainer", "SaaS"] },
  { t: "Retainer", c: "Business and Revenue", d: "A recurring service agreement providing defined support, production, access, or strategic responsibility.", r: ["Subscription", "Recurring Revenue"] },
  { t: "SaaS", c: "Business and Revenue", d: "Software as a service. Software customers access through a recurring subscription rather than buying a single permanent copy.", r: ["Subscription"] },
  { t: "Marketplace Revenue", c: "Business and Revenue", d: "Income generated by facilitating transactions between groups — often through fees, commissions, subscriptions, or promoted placement.", r: ["Marketplace"] },
  { t: "Upsell", c: "Business and Revenue", d: "A relevant additional purchase that expands the original result.", r: ["Cross-Sell"] },
  { t: "Cross-Sell", c: "Business and Revenue", d: "A related service or product offered alongside the primary purchase.", r: ["Upsell"] },
  { t: "Recurring Revenue", c: "Business and Revenue", d: "Income that repeats through subscriptions, retainers, memberships, licensing, or continuing services.", r: ["Subscription", "Retainer"] },
  { t: "Customer Acquisition Cost", c: "Business and Revenue", d: "The estimated cost required to gain a new customer.", r: ["Lifetime Value"] },
  { t: "Lifetime Value", c: "Business and Revenue", d: "The estimated total value of a customer relationship over time.", r: ["Customer Acquisition Cost"] },
  { t: "Gross Margin", c: "Business and Revenue", d: "Revenue remaining after direct delivery costs are removed.", r: ["Business Model"] },
  { t: "Pilot", c: "Business and Revenue", d: "A controlled early program used to test the service, system, or partnership before wider expansion.", r: ["Licensing"] },
  { t: "Licensing", c: "Business and Revenue", d: "Permission for another party to use approved intellectual property, content, systems, or technology under defined terms.", r: ["Intellectual Property"] },

  /* ---- Safety, Ownership, and Access ---- */
  { t: "Intellectual Property", c: "Safety, Ownership, and Access", d: "Original creations such as code, designs, names, content, systems, documentation, inventions, and brand assets.", r: ["Source Code", "Licensing"] },
  { t: "Source Code", c: "Safety, Ownership, and Access", d: "The editable instructions used to create software. The project agreement should clearly state what source access and ownership the client receives.", r: ["Ownership and Handoff"] },
  { t: "NDA", c: "Safety, Ownership, and Access", d: "Nondisclosure agreement — a legal agreement establishing confidentiality responsibilities. It does not automatically protect every legal interest; seek legal review when needed.", r: ["Black Vault Protocol™"] },
  { t: "Privacy", c: "Safety, Ownership, and Access", d: "The responsible handling of personal and sensitive information.", r: ["Consent", "Compliance"] },
  { t: "Consent", c: "Safety, Ownership, and Access", d: "Clear permission from a person before collecting, storing, tracking, contacting, or using certain information.", r: ["Privacy"] },
  { t: "Access Control", c: "Safety, Ownership, and Access", d: "Rules limiting which people or systems can view, edit, export, or manage information.", r: ["Authorization", "Encryption"] },
  { t: "Encryption", c: "Safety, Ownership, and Access", d: "A method of protecting data by converting it into a form unauthorized parties cannot easily read.", r: ["Access Control"] },
  { t: "Compliance", c: "Safety, Ownership, and Access", d: "Meeting specific legal, regulatory, contractual, or industry requirements. We don't claim a product is compliant unless the required review and implementation have actually occurred.", r: ["Privacy", "Security Review"] },
  { t: "Quality Assurance", c: "Safety, Ownership, and Access", d: "Testing whether the product functions correctly, consistently, and according to the approved scope.", r: ["Acceptance Criteria", "Security Review"] },
  { t: "Security Review", c: "Safety, Ownership, and Access", d: "An assessment of potential risks, access, permissions, storage, dependencies, and system behavior.", r: ["Compliance"] },
  { t: "Ownership and Handoff", c: "Safety, Ownership, and Access", d: "The documented process explaining what the client receives, where it is stored, how it is accessed, and what responsibilities remain after delivery.", r: ["Source Code", "Intellectual Property"] }
];
